<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <link name="depth_camera_link">
    <visual>
      <geometry>
        <box size="0.025 0.125 0.03"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <xacro:inertial_box mass="0.1" length="0.025" breadth="0.125" height="0.03">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:inertial_box>
  </link>
  <joint name="depth_camera_joint" type="fixed">
    <parent link="chassis_link"/>
    <child link="depth_camera_link"/>
    <origin xyz="0.155 0 ${chassis_height/2 + 0.015}" rpy="0 0 0"/>
  </joint>

  <gazebo reference="depth_camera_link">
    <material>Gazebo/Silver</material>
    <sensor name="depth_camera" type="depth_camera">
      <pose> 0 0 0 0 0 0 </pose>
      <topic>depth_camera</topic>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <camera>
        <horizontal_fov>1.05</horizontal_fov>
        <image>
          <width>256</width>
          <height>256</height>
          <format>R_FLOAT32</format>
        </image>
        <clip>
          <near>0.1</near>
          <far>10.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

</robot>
