<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <link name="depth_camera_link">
    <visual>
      <geometry>
        <box size="0.025 0.125 0.03" />
      </geometry>
      <material name="silver" />
    </visual>
    <xacro:inertial_box mass="0.1" length="0.025" breadth="0.125" height="0.03">
      <origin xyz="0 0 0" rpy="0 0 0" />
    </xacro:inertial_box>
  </link>
  <joint name="depth_camera_joint" type="fixed">
    <parent link="chassis_link" />
    <child link="depth_camera_link" />
    <origin xyz="0.155 0 ${chassis_height/2 + 0.015}" rpy="0 0 0" />
  </joint>

  <gazebo reference="depth_camera_link">
    <material>Gazebo/Silver</material>
    <sensor name="depth_camera" type="depth_camera">
      <always_on>1</always_on>
      <visualize>0</visualize>
      <update_rate>30</update_rate>
      <topic>sensors/camera</topic>
      <!-- <ignition_frame_id>depth_camera_link</ignition_frame_id> -->
      <!-- A bug in depth_camera sensor does not allow setting frame_id for point clouds:
      https://github.com/gazebosim/gz-sensors/pull/350 -->
      <!-- It defaults to "robot/base_link/depth_camera" and can be handled either using a static
      transformer or topic_tools-->
      <pose relative_to='depth_camera_link'>0 0 0 0 0 0</pose>
      <camera>
        <horizontal_fov>1.089</horizontal_fov>
        <image>
          <format>R_FLOAT32</format>
          <width>640</width>
          <height>480</height>
        </image>
        <clip>
          <near>0.05</near>
          <far>10.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

</robot>
