joy:
  ros__parameters:
    # device_name: Sony Interactive Entertainment Wireless Controller
    # device_name: Wireless Controller
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

teleop_twist_joy:
  ros__parameters:
    axis_linear: # Forward/Back
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0
    axis_angular: # Left/Right
      yaw: 3
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0
    enable_button: 4
    enable_turbo_button: 6

teleop_gateway:
  ros__parameters:
    wheelbase: 0.33
    min_allowed_linear_velocity: 0.05 #m/s
    min_allowed_angular_velocity: 0.01 #rad/s
    reverse_steer_correction_topics: ["joy_vel"]
    emergency_stop_set_joy_button_index: 5
    emergency_stop_clear_joy_button_index: 7
    joy_emergency_stop_timeout: 1.0 #seconds
    start_with_emergency_stop: true
    enable_keyboard: false

twist_mux:
  ros__parameters:
    topics:
      joystick:
        topic   : joy_vel_corrected
        timeout : 0.5
        priority: 100
      keyboard:
        topic   : key_vel
        timeout : 0.5
        priority: 90
