track_test_runner_node:
  ros__parameters:
    use_sim_time: false
    orchestrate_test_setup: true
    track_test_runner_timer_rate: 1.0
    test_config_start_index: 1
    test_config_end_index: 0
    test_configurations_json_path: "truck_small_scale_track_test_configurations.json"
    rosbag_output_dir: "track_test_data" # relative path
    use_rosbag_recording: true
    mission_status_topic: "/truck/mission_status"
    autopilot_state_control_topic: "/truck/autopilot_state_control"
    end_test_after_mission_complete: true
    preplanned_route_filepath: "$WAYWISER_WS/resources/small_scale_route.xml"
    vehicle_start_position_is_test_start_point: true
    # test_start_point: "-0.24136670548847863, 0.9810376247909707, 0.0, 0.0, 0.0, -0.6382656725442453, 0.7698161671799588"
    vehicle_pose_topic: "/truck/rear_axle_pose"
    trailer_pose_topic: "/semitrailer/rear_axle_pose"
    emergency_stop_topic: "/emergency_stop/current_state"
    end_goal_alignment_type: 0 # Align {0: REAR_AXLE, 1: FRONT_REAR_END, 2: CENTER} with the end goal
    end_goal_alignment_threshold: 0.1 # m
    continue_test_after_estop_clear: false
    enuref: [57.713805, 12.890088, 203.59] # [lat, lon, height]
    test_timeout: 400.0
    test_cooldown_time: 10.0
    halt_test_runner_on_timeout: true
    notify_via_mail_on_timeout: true
    notify_via_mail_on_completion: true

    rear_axle_frame: truck_rear_axle_link
    rear_end_frame: truck_rear_end_link
    hitch_frame: truck_fifth_wheel_link

    trailer_rear_axle_frame: semitrailer_rear_axle_link
    trailer_rear_end_frame: semitrailer_rear_end_link
    trailer_hitch_frame: semitrailer_kingpin_link

    has_trailer: true
    length: 0.505
    width: 0.185
    wheelbase: 0.2866
    trailer_length: 0.980
    trailer_width: 0.187
    trailer_wheelbase: 0.6150
    staging_area_margin: 0.1
    trace_topic: "/semitrailer/rear_axle_pose"

    topics_to_record:
      [
        "/waywiser_control_cmd",
        "/cmd_vel_out",
        "/emergency_stop/current_state",
        "/emergency_stop/target_state",
        "/onboard_mux_vel",
        "/semitrailer/rear_axle_pose",
        "/truck/autopilot_center_pose",
        "/truck/autopilot_state_control",
        "/truck/mission_status",
        "/truck/odometry",
        "/truck/rear_axle_pose",
        "/truck/sensors/gnss/nav_pvt_pose",
        "/truck/sensors/gnss/nav_sat_fix",
        "/truck/sensors/gnss/nav_sat_info",
        "/truck/sensors/gnss/rtcm_frequency",
        "/truck/sensors/ultrasonic/trailer_left",
        "/truck/sensors/ultrasonic/trailer_rear",
        "/truck/sensors/trailer_angle",
        "/truck/vehicle_alignment_reference_point",
        "/waywiser_vel",
        "/waywiser_path",
      ]
