/**:
  # general parameters shared by all agrarsense nodes
  ros__parameters:
    ros_async: true
    ros_host_ip: "127.0.0.1"
    ros_port: 9090
    map_name: "playground" # possible options: playground, vindeln, rovaniemiforest
    ego_vehicle_identifier: "forwarder"
    rgbd_to_pointcloud_sources: ["front"]
    front:
      attached_to: "forwarder"
      rgb_camera: "rgb_front"
      depth_camera: "depth_front"

sim_orchestrator_node:
  ros__parameters:
    sim_script_path: "~/workspaces/agrarsense_ws/Agrarsense.sh"
    ros_bridge_script_path: "agrarsense_ros_bridge.sh"
    docker_container_name: "agrarsense_ros_bridge"
    sigterm_timeout: 20.0
    sim_in_command_topic: "/agrarsense/in/commands"
    workersthreadpool: 0 #By default the Simulator uses maximum number of CPU threads - 1
    spectator_rendering: true
    quality_level: "Balanced" #"Ultra", "Balanced" or "Low"
    # spectator_transform: "85,2650,1200,0,270,0"
    sim_startup_time: 10.0
    command_publish_delay: 5.0
    objects_json_path: "playground_objects.json"
    sim_configurations_json_path: "sim_configurations.json"
    rosbag_output_dir: "sim_data" # relative path
    use_rosbag_recording: false
    autostart_simulations: true
    auto_spawn_objects: true
