joy:
  ros__parameters:
    # device_name: Sony Interactive Entertainment Wireless Controller
    # device_name: Wireless Controller
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:
    default:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: cmd_vel_out
      deadman_buttons: [4]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 1.0
          offset: 0.0
        angular-z:
          axis: 3
          scale: 0.5
          offset: 0.0

    human_control:
      type: topic
      interface_type: geometry_msgs/msg/Twist
      topic_name: cmd_vel_out
      deadman_buttons: [4]
      axis_mappings:
        linear-x:
          axis: 1
          scale: 1.0
          offset: 0.0
        angular-z:
          axis: 3
          scale: 0.5
          offset: 0.0
