joy:
  ros__parameters:
    # device_name: Sony Interactive Entertainment Wireless Controller
    # device_name: Wireless Controller
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

teleop_twist_joy_node:
  ros__parameters:
    axis_linear: # Forward/Back
      x: 1
    scale_linear:
      x: 0.5
    scale_linear_turbo:
      x: 1.0
    axis_angular: # Left/Right
      yaw: 3
    scale_angular:
      yaw: 0.5
    scale_angular_turbo:
      yaw: 1.0
    enable_button: 4
    enable_turbo_button: 6
