enable_color: true
rgb_camera.profile: 640x480x5
rgb_camera.color_format: "RGB8"
enable_depth: true
depth_module.profile: 640x480x5
depth_module.depth_format: "Z16"
align_depth.enable: true
enable_infra: false
enable_infra1: false
enable_infra2: false
enable_rgbd: false
enable_gyro: false
enable_accel: false
pointcloud.enable: true
colorizer.enable: false
enable_sync: true
publish_tf: false
tf_publish_rate: 30.0
