/**:
  # general parameters shared by all waywise-related nodes
  ros__parameters:
    odom_frame: odom
    base_frame: base_link
    erpm_min: -10000.0
    erpm_max: 10000.0
    speed_to_erpm_factor: 4500.0
    wheelbase: 0.33
    min_turning_radius: 0.92
    max_angular_velocity: 0.5
    standstill_velocity_threshold: 0.05

waywise_rover_node:
  ros__parameters:
    servo_min: 0.0
    servo_max: 0.9
    servo_offset: 0.45
    #steering_angle_to_servo_gain: -0.950
    invert_servo_output: false
    # TODO: limit erpm also based on current
    # current_max: 30.0
    publish_odom_to_baselink_tf: true
    odom_publish_rate: 30 # currently same rate for both odom topic and odom->base_link tf
    enable_imu_for_odom: false
    enable_lidar: false
    enable_camera: false

waywise_autopilot_node:
  ros__parameters:
    autopilot_cmd_publish_rate: 30
    waywise_control_tower_address: "127.0.0.1"
