/**:
  # general parameters shared by all waywise-related nodes
  ros__parameters:
    odom_frame: odom
    base_frame: truck
    world_frame: map
    rear_axle_frame: truck_rear_axle_link
    center_frame: truck_chassis_link
    rear_end_frame: truck_rear_end_link
    hitch_frame: truck_fifth_wheel_link
    erpm_min: -10000.0
    erpm_max: 10000.0
    speed_to_erpm_factor: 5190.0
    length: 0.5
    width: 0.21
    wheelbase: 0.3
    min_turning_radius: 0.67 # wheelbase/tan(max_steering_angle)
    max_angular_velocity: 2.5 # rad/s
    standstill_velocity_threshold: 0.05
    odom_topic: "/truck/odometry"
    has_trailer: true
    trailer_base_frame: semitrailer
    trailer_rear_axle_frame: semitrailer_rear_axle_link
    trailer_center_frame: semitrailer_chassis_link
    trailer_rear_end_frame: semitrailer_rear_end_link
    trailer_hitch_frame: semitrailer_kingpin_link
    trailer_length: 0.96
    trailer_width: 0.21
    trailer_wheelbase: 0.64
    angle_sensor_topic: "/truck/sensors/trailer_angle"
    urdf_file: "semitruck.urdf.xacro"
    urdf_scale: 0.071429 # 1:14
    front_steering_joint_names: ["truck_fls_link_joint", "truck_frs_link_joint"]
    front_wheel_joint_names: ["truck_flw_link_joint", "truck_frw_link_joint"]
    rear_wheel_joint_names:
      [
        "truck_mlw_link_joint",
        "truck_mrw_link_joint",
        "truck_rlw_link_joint",
        "truck_rrw_link_joint",
      ]
    trailer_wheel_joint_names:
      [
        "semitrailer_flw_link_joint",
        "semitrailer_frw_link_joint",
        "semitrailer_mlw_link_joint",
        "semitrailer_mrw_link_joint",
        "semitrailer_rlw_link_joint",
        "semitrailer_rrw_link_joint",
      ]
    truck_trailer_link_joint_name: "truck_trailer_link_joint"

waywise_truck_node:
  ros__parameters:
    servo_min: 0.0
    servo_max: 0.5
    servo_offset: 0.42
    #steering_angle_to_servo_gain: -0.950
    invert_servo_output: true
    # TODO: limit erpm also based on current
    # current_max: 30.0
    publish_odom_to_baselink_tf: true
    publish_world_to_odom_tf: true
    update_world_position_with_odom: false
    update_world_position_with_tf: false
    odom_publish_rate: 30 # currently same rate for both odom topic and odom->base_link tf
    imu_for_position_fusion: "vesc"
    tof_sensors: [tof_trailer_rear, tof_trailer_right, tof_trailer_left]
    tof_trailer_rear:
      i2c_addr: 0x29
      topic: "/truck/sensors/tof/trailer_rear"
    # tof_trailer_right:
    #   i2c_addr: 0x30
    #   topic: "/truck/sensors/tof/trailer_right"
    # tof_trailer_left:
    #   i2c_addr: 0x31
    #   topic: "/truck/sensors/tof/trailer_left"
    joint_states_publish_rate: 10
    invert_trailer_joint_state: true
    start_with_autopilot: false
    autopilot_twist_publish_rate: 30
    waywise_control_tower_address: "127.0.0.1"
    waywise_control_tower_port: 14540
    purepursuit_radius: 1.5
    purepursuit_forward_gain: 1.0
    purepursuit_reverse_gain: -1.0
    adaptive_pure_pursuit: true
    preplanned_route_filepath: ""
    end_goal_alignment_type: 1 # Align {0: REAR_AXLE, 1: FRONT_REAR_END, 2: CENTER} with the end goal
    mission_status_topic: "/truck/mission_status"
    autopilot_state_control_topic: "/truck/autopilot_state_control"
    vehicle_pose_topic: "/truck/rear_axle_pose"
    trailer_pose_topic: "/semitrailer/rear_axle_pose"
    vehicle_alignment_reference_point_topic: "/truck/vehicle_alignment_reference_point"
    autopilot_center_pose_topic: "/truck/autopilot_center_pose"
    nav_sat_fix_topic: "/truck/sensors/gnss_fix"
    battery_voltage_topic: "/truck/sensors/battery_voltage"
    min_battery_voltage: 19.2

emergency_stop_monitor:
  ros__parameters:
    start_with_emergency_stop: true
    cmd_vel_in_timeout: 0.5
    emergency_stop_state_publish_rate: 10

onboard_twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      teleop:
        topic: teleop_mux_vel
        timeout: 0.5
        priority: 100
      nav2:
        topic: nav2_vel
        timeout: 0.5
        priority: 50
