<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.025 0.125 0.03"/>
      </geometry>
      <material name="silver"/>
    </visual>
    <xacro:inertial_box mass="0.1" x="0.025" y="0.125" z="0.03">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:inertial_box>
  </link>
  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="0.155 0 ${base_height/2 + 0.05}" rpy="0 0 0"/>
  </joint>

  <link name="camera_link_optical"></link>
  <joint name="camera_optical_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_link_optical"/>
    <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
  </joint>

  <gazebo reference="camera_link">
    <material>Gazebo/Black</material>
    <sensor name="camera" type="camera">
      <pose> 0 0 0 0 0 0 </pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <camera>
        <horizontal_fov>1.089</horizontal_fov>
        <image>
          <format>R8G8B8</format>
          <width>640</width>
          <height>480</height>
        </image>
        <clip>
          <near>0.05</near>
          <far>8.0</far>
        </clip>
      </camera>
    </sensor>
  </gazebo>

</robot>
