<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.075 0.075 0.02"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="0.075 0.075 0.2"/>
      </geometry>
    </collision>
    <xacro:inertial_box mass="0.1" x="0.075" y="0.075" z="0.02">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:inertial_box>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.08 0 ${base_height/2 + 0.01}"/>
  </joint>

  <gazebo reference="imu_link">
    <material>Gazebo/Black</material>
    <sensor name="imu_sensor" type="imu">
        <always_on>1</always_on>
        <update_rate>1</update_rate>
        <visualize>true</visualize>
        <topic>imu</topic>
    </sensor>
  </gazebo>

</robot>
