<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <link name="lidar_frame">
    <visual>
      <geometry>
        <cylinder radius="0.025" length="0.03"/>
      </geometry>
      <material name="black"/>
    </visual>
    <visual>
      <origin xyz="0 0 -0.05"/>
      <geometry>
        <cylinder radius="0.01" length="0.1"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="0.025" length="0.03"/>
      </geometry>
    </collision>
    <xacro:inertial_cylinder mass="0.01" length="0.025" radius="0.03">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>
  </link>

  <joint name="lidar_joint" type="fixed">
    <parent link="base_link"/>
    <child link="lidar_frame"/>
    <origin xyz="0.11 0 ${base_height/2 + 0.095}" rpy="0 0 ${pi}"/>
  </joint>

  <gazebo reference="lidar_frame">
    <material>Gazebo/Black</material> 
    <sensor name='lidar' type='gpu_lidar'>"
      <pose relative_to='lidar_frame'>0 0 0 0 0 0</pose>
      <topic>lidar</topic>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>640</samples>
            <resolution>1</resolution>
            <min_angle>-1.396263</min_angle>
            <max_angle>1.396263</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>0.01</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.08</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <alwaysOn>1</alwaysOn>
      <visualize>true</visualize>
    </sensor>
  </gazebo>

</robot>
