# Full set of configurations
- ros_topic_name: "/drone/sensors/camera/color/image_rect"
  gz_topic_name: "/sensors/drone/camera/image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: false               # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Ignition

- ros_topic_name: "/drone/sensors/camera/aligned_depth_to_color/image_rect"
  gz_topic_name: "/sensors/drone/camera/depth_image"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: false               # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Ignition

- ros_topic_name: "/drone/sensors/camera/aligned_depth_to_color/camera_info"
  gz_topic_name: "/sensors/drone/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: false               # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Ignition


- ros_topic_name: "/drone/sensors/camera/depth/points"
  gz_topic_name: "/sensors/drone/camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: false               # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Ignition

- ros_topic_name: "/drone/sensors/camera/color/points"
  gz_topic_name: "/sensors/drone/camera/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: false               # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Ignition

- ros_topic_name: "/drone/sensors/gnss/navsat"
  gz_topic_name: "/drone/gps/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: false               # Default "false"
  direction: GZ_TO_ROS

- ros_topic_name: "/drone/sensors/imu/raw"
  gz_topic_name: "/drone/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: false               # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Ignition

- ros_topic_name: "/drone/joint_states"
  gz_topic_name: "/drone/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: false               # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gazebo

- ros_topic_name: "/drone/cmd_vel_out"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_topic_name: "/drone/cmd_vel"
  gz_type_name: "gz.msgs.Twist"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: true                # Default "false"
  direction: ROS_TO_GZ      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Gazebo

- ros_topic_name: "tf"
  gz_topic_name: "/model/drone/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  subscriber_queue: 5       # Default 10
  publisher_queue: 6        # Default 10
  lazy: false               # Default "false"
  direction: GZ_TO_ROS      # Default "BIDIRECTIONAL" - Bridge both directions
                            # "GZ_TO_ROS" - Bridge Ignition topic to ROS
                            # "ROS_TO_GZ" - Bridge ROS topic to Ignition
