/**:
  # general parameters shared by all waywise-related nodes.
  # - frame_prefix is used to prefix all frame names with a common prefix
  #   this is useful when running multiple vehicles in the same simulation with same configuration
  # - namespace is used to prefix all topic names with a common prefix
  ros__parameters:
    frame_prefix: "/"
    odom_frame: odom
    base_frame: base_link
    world_frame: map
    gnss_reference_frame: base_link
    enuref: [57.713805, 12.890088, 203.59] # [lat, lon, height]

    urdf_file: "drone.urdf.xacro"
    urdf_scale: 1.0 # 1:1
    urdf_extra_args: "sim_mode:=true"

    odom_topic: "odometry"
    nav_sat_fix_extended_topic: "sensors/gnss/nav_sat_fix_extended"
    fused_nav_sat_fix_extended_topic: "sensors/gnss/fused_nav_sat_fix_extended"
    rtcm_frequency_topic: "rtcm_frequency"
    imu_topic: "sensors/imu/raw"
    gnss_chip_orientation_offset: [0, 0, 0.0]

waywiser_drone_localization_node:
  ros__parameters:
    use_sdvp_position_fusion: false
    gnss_variant: "external"
    gnss_reference_frame: base_link
    ext_startup_timeout: 5.0
    tf_publish_rate: 0

navsatfix_extended_wrapper_node:
  ros__parameters:
    # conversion_mode: "navsatfix"
    # nav_sat_fix_input_topic: "sensors/gnss/navsat"
    conversion_mode: "tf"
    tf_object_frame: "drone"
    frame_id_override: "base_link"
    gnss_fix_type: 3
    gnss_horizontal_accuracy: 0.01
    gnss_vertical_accuracy: 0.01
    gnss_heading_accuracy: 0.1
    gnss_last_rtcm_correction_age: 0
    gnss_num_satellites: 0
