/**:
  # general parameters
  ros__parameters:
    ego_vehicle_role_name: truck
    role_name: truck
    host: localhost
    port: 2000
    timeout: 20
    town: GbgSaroRound

carla_osm_tile_server_node:
  ros__parameters:
    tcp_server_ip: localhost
    tcp_server_port: 8080
    carla_world_origin_offset_x: 0.0
    carla_world_origin_offset_y: 0.0
    reset_base_map_image: false
    carla_bev_view_camera_resolution: 640
    carla_bev_view_camera_fov: 10.0
    carla_bev_view_camera_height: 1500.0
    image_processing_workers: 16
    rendering_wait_ticks: 10
    map_region: [1400.0, 1800.0, -800.0, -1200.0] # Top, right, bottom, left
    # map_region: [0.0, 0.0, 0.0, 0.0] # Top, right, bottom, left
