/**:
  # general parameters shared by all carla nodes
  ros__parameters:
    ego_vehicle_role_name: truck
    role_name: truck
    host: localhost
    port: 2000
    timeout: 10
    town: Sunrise_from_Town05
    rgbd_to_pointcloud_sources: ["front", "dock"]
    front:
      attached_to_ego_vehicle: true
      rgb_camera: "rgb_front"
      depth_camera: "depth_front"
    dock:
      attached_to_ego_vehicle: false
      rgb_camera: "rgb_dock"
      depth_camera: "depth_dock"

carla_orchestrator_node:
  ros__parameters:
    carla_script_path: "~/workspaces/carla_ws/CarlaUE4.sh"
    sim_startup_time: 5.0
    render_off_screen: false
    reset_carla_after_exec: false
    carla_ros_bridge:
      passive: false
      synchronous_mode: true
      synchronous_mode_wait_for_vehicle_control_command: false
      fixed_delta_seconds: 0.05
      register_all_sensors: true
    sim_configurations_json_path: "sim_configurations.json"
    objects_json_path: "dts_truck_semitrailer.json"
    weather: "ClearNoon"
    rosbag_output_dir: "sim_data" # relative path
    use_rosbag_recording: false
    static_tf_publishers: ["dock_to_map_static_tf"]
    dock_to_map_static_tf:
      frame_id: "dock"
      parent_frame_id: "map"
      transform_to_parent: "1.7,68.4,5.2,0.0,0.0,-90.0"

carla_osm_tile_server_node:
  ros__parameters:
    tcp_server_ip: localhost
    tcp_server_port: 8080
    carla_world_origin_offset_x: 0.0
    carla_world_origin_offset_y: 0.0
    reset_base_map_image: false
    aerial_view_camera_resolution: 1920
    aerial_view_camera_fov: 5.0
    aerial_view_camera_height: 1500.0

waywiser_twist_to_carla_control_node:
  ros__parameters:
    speed_control_threshold: 0.5 # in m/s
    max_steering_angle: 0.7
    max_throttle: 1.0
    max_brake: 1.0
    speed_control_kp: 0.5
    speed_control_ki: 0.1
    speed_control_kd: 0.05
    speed_control_loop_rate: 20
