/**:
  # general parameters shared by all waywise-related nodes
  ros__parameters:
    odom_frame: truck
    base_frame: truck
    erpm_min: -30000.0
    erpm_max: 30000.0
    speed_to_erpm_factor: 4500.0
    length: 6.97
    width: 2.98
    wheelbase: 3.1
    min_turning_radius: 2.54 # wheelbase/tan(max_steering_angle)
    max_angular_velocity: 0.5 # rad/s
    standstill_velocity_threshold: 0.05
    odom_topic: "/carla/truck/odometry"
    trailer_length: 13.7
    trailer_width: 2.51
    trailer_wheelbase: 9.0
    angle_sensor_topic: "sensors/truck/angle"

waywise_truck_autopilot_node:
  ros__parameters:
    has_trailer: true
    autopilot_cmd_publish_rate: 30
    waywise_control_tower_address: "127.0.0.1"
    purepursuit_radius: 20.0
    purepursuit_forward_gain: 1.0
    purepursuit_reverse_gain: -1.0
    adaptive_pure_pursuit: true

emulated_angle_sensor:
  ros__parameters:
    enable: true
    primary_frame: truck
    secondary_frame: semitrailer
    publish_rate: 10
    invert_angle: true
