/**:
  # general parameters shared by all waywise-related nodes
  ros__parameters:
    base_frame_id: "truck"
    odom_frame_id: "odom"
    odom_frame: odom
    base_frame: truck
    world_frame: map
    rear_axle_frame: truck_rear_axle_link
    chassis_frame: truck_chassis_link
    rear_end_frame: truck_rear_end_link
    hitch_frame: truck_fifth_wheel_link
    gnss_chip_frame: truck_gnss_chip_link
    gnss_antenna_frame: truck_gnss_antenna_link

    trailer_base_frame: semitrailer_base_link
    trailer_rear_axle_frame: semitrailer_rear_axle_link
    trailer_center_frame: semitrailer_chassis_link
    trailer_rear_end_frame: semitrailer_rear_end_link
    trailer_hitch_frame: semitrailer_kingpin_link

    front_steering_joint_names: ["truck_fls_link_joint", "truck_frs_link_joint"]
    front_wheel_joint_names: ["truck_flw_link_joint", "truck_frw_link_joint"]
    rear_wheel_joint_names:
      [
        "truck_mlw_link_joint",
        "truck_mrw_link_joint",
        "truck_rlw_link_joint",
        "truck_rrw_link_joint",
      ]
    trailer_wheel_joint_names:
      [
        "semitrailer_flw_link_joint",
        "semitrailer_frw_link_joint",
        "semitrailer_mlw_link_joint",
        "semitrailer_mrw_link_joint",
        "semitrailer_rlw_link_joint",
        "semitrailer_rrw_link_joint",
      ]
    truck_trailer_link_joint_name: "truck_trailer_link_joint"
    has_trailer: true
    length: 7.07
    width: 2.59
    wheelbase: 4.0124
    track_width: 2.05
    trailer_length: 13.72
    trailer_width: 2.618
    trailer_wheelbase: 8.61

    erpm_min: 440.0
    erpm_max: 28000.0
    speed_to_erpm_factor: 528.0
    # max_outer_steering_angle: 70.0 # degrees set in carla
    min_turning_radius: 1.29156022 # wheelbase/tan(max_outer_steering_angle) - track_width/2
    enuref: [57.713805, 12.890088, 203.59] # [lat, lon, height]

    rear_axle_frame_to_base_frame_offset: [1.9655, 0.0000, -0.5197]
    rear_axle_frame_to_center_frame_offset: [1.9655, 0.0000, 0.4153]
    rear_axle_frame_to_rear_end_frame_offset: [-1.7878, 0.0000, 0.4153]
    gnss_antenna_to_gnss_chip_offset: [0.1003, 0.6642, -2.2783]
    gnss_chip_orientation_offset: [0.0000, -0.0000, 0.0000]
    rear_axle_frame_to_hitch_frame_offset: [-0.2437, 0.0000, 0.6961]
    trailer_rear_axle_frame_to_trailer_base_frame_offset:
      [4.0880, 0.0000, -0.5197]
    trailer_rear_axle_frame_to_trailer_rear_end_frame_offset:
      [-2.7801, 0.0000, 0.3847]
    trailer_rear_axle_frame_to_trailer_center_frame_offset:
      [4.0880, 0.0000, 0.6929]
    trailer_rear_axle_frame_to_trailer_hitch_frame_offset:
      [9.4968, 0.0000, 0.6929]

    enable_visualization_msgs: true

    urdf_file: "semitruck.urdf.xacro"
    urdf_scale: 1.0 # 1:1
    urdf_extra_args: "has_trailer:=true"

    odom_topic: "odometry"
    vehicle_pose_topic: "rear_axle_pose"
    trailer_pose_topic: "semitrailer/rear_axle_pose"
    angle_sensor_topic: "sensors/trailer_angle"
    rtcm_frequency_topic: "sensors/gnss/rtcm_frequency"
    nav_pvt_pose_topic: "sensors/gnss/nav_pvt_pose"
    battery_state_topic: "sensors/battery_state"
    mission_status_topic: "mission_status"
    autopilot_state_control_topic: "autopilot_state_control"
    vehicle_alignment_reference_point_topic: "vehicle_alignment_reference_point"
    autopilot_center_pose_topic: "autopilot_center_pose"
    emergency_stop_status_topic: "emergency_stop/current_state"
    emergency_stop_update_topic: "emergency_stop/target_state"
    nav_sat_fix_extended_topic: "sensors/gnss/nav_sat_fix_extended"
    fused_nav_sat_fix_extended_topic: "sensors/gnss/fused_nav_sat_fix_extended"

    gnss_reference_frame: "truck"
    gnss_message_rate: 30 # Hz

    vehicle_control_command_topic: "waywiser_control_cmd"
    autopilot_vel_topic: "waywiser_autopilot_vel"
    joint_states_topic: "waywiser_joint_states"
    imu_topic: "sensors/imu/raw"

emulated_angle_sensor_node:
  ros__parameters:
    base_frame: truck
    trailer_base_frame: semitrailer
    angle_offset: 0.0
    publish_rate: 50
    invert_angle: false
    angle_sensor_topic: "sensors/trailer_angle"

emulated_range_sensor_array_node:
  ros__parameters:
    sensor_ids:
      ["semitrailer_left_range_sensor", "semitrailer_rear_range_sensor"]
    semitrailer_left_range_sensor:
      frame_id: semitrailer_left_ultrasonic_link
      depth_topic: "/carla/semitrailer/left_ultrasonic/image"
      range_topic: "sensors/ultrasonic/trailer_left"
      min_range: 0.1
      max_range: 10.0
      field_of_view: 30.0
      radiation_type: 0 # 0: ULTRASOUND, 1: INFRARED
    semitrailer_rear_range_sensor:
      frame_id: semitrailer_rear_ultrasonic_link
      depth_topic: "/carla/semitrailer/rear_ultrasonic/image"
      range_topic: "sensors/ultrasonic/trailer_rear"
      min_range: 0.1
      max_range: 10.0
      field_of_view: 30.0
      radiation_type: 0 # 0: ULTRASOUND, 1: INFRARED

waywiser_truck_node:
  ros__parameters:
    vehicle_interface_type: "ext_simulated"
    speed_control_type: "closed_loop_pid_speed_control"
    pid_speed_controller_gains: [1.0, 0.01, 0.05]
    servo_offset: 0.472
    servo_range: 0.4 # servo_output = servo_offset + [-servo_range/2, servo_range/2]
    invert_servo_output: false
    invert_steering_feedback_from_odom: true
    # TODO: limit erpm also based on current
    # current_max: 30.0
    waypoint_follower_bypass_mux: false
    publish_odom_to_baselink_tf: true
    publish_world_to_odom_tf: true
    vehicle_state_poll_rate: 50 # currently same rate for both odom topic and odom->base_link tf
    min_battery_voltage: 13.6
    joint_states_publish_rate: 10
    invert_trailer_joint_state: true
    autopilot_timer_rate: 50
    enable_mavlink_interface: true
    waywise_control_tower_address: "127.0.0.1"
    waywise_control_tower_port: 14540
    purepursuit_radius: 8.0 # m
    purepursuit_forward_gain: 1.0
    purepursuit_reverse_gain: -0.4
    adaptive_pure_pursuit: true
    end_goal_alignment_type: 0 # Align {0: REAR_AXLE, 1: FRONT_REAR_END, 2: CENTER} with the end goal
    end_goal_alignment_threshold: 0.1 # m
    adaptive_approach_speed_enabled: true
    min_approach_speed: 1.39 # m/s
    yaw_accuracy_threshold_for_mission: 1.0 # degrees
    position_accuracy_threshold_for_mission: 0.7 # m
    invert_steering_joint_state: true

waywiser_truck_localization_node:
  ros__parameters:
    use_sdvp_position_fusion: false
    gnss_variant: "external"

navsatfix_extended_wrapper_node:
  ros__parameters:
    conversion_mode: "tf"
    tf_object_frame: "truck"
    frame_id_override: "truck_base_link"
    gnss_fix_type: 3
    gnss_horizontal_accuracy: 0.01
    gnss_vertical_accuracy: 0.01
    gnss_heading_accuracy: 0.1
    gnss_last_rtcm_correction_age: 0
    gnss_num_satellites: 0

waywiser_carla_relay_node:
  ros__parameters:
    steering_gain: 0.857142857

emergency_stop_monitor:
  ros__parameters:
    start_with_emergency_stop: false
    cmd_vel_in_timeout: 0.5
    emergency_stop_state_publish_rate: 10

onboard_twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic: teleop_mux_vel
        timeout: 0.5
        priority: 100
      waywise:
        topic: waywiser_autopilot_vel
        timeout: 0.5
        priority: 60
      nav2:
        topic: nav2_vel
        timeout: 0.5
        priority: 50
