<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>waywiser_agrarsense</name>
  <version>0.0.0</version>

  <description>Interface between WayWiser and Agrarsense simulator (built on UE5)</description>

  <maintainer email="ramana.reddy.avula@ri.se">Ramana Avula</maintainer>

  <license>GPLv3</license>

  <url type="website">https://dev.azure.com/AMKFrostBit/AGRARSENSE</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>topic_tools</depend>
  <depend>geometry_msgs</depend>
  <depend>tf_transformations</depend>
  <exec_depend>waywiser</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
