name: Build Packages

on:
  pull_request:
    branches:
      - humble
  push:
    branches:
      - humble

  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container: ghcr.io/rise-dependable-transport-systems/waywiser/ci-image:humble

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate repos file with carla-ros-bridge
        run: |
          cat << 'EOF' > /tmp/deps.repos
          repositories:
            carla_ros_bridge:
              type: git
              url: https://github.com/RISE-Dependable-Transport-Systems/carla-ros-bridge.git
              version: v0.9.15-humble-dev
          EOF

      - name: Cache ccache
        uses: actions/cache@v4
        with:
          path: /root/.ccache
          key: ${{ runner.os }}-ccache-humble-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ccache-humble-

      - name: Run Tests
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: waywiser waywiser_agrarsense waywiser_carla waywiser_core waywiser_description waywiser_gazebo waywiser_hwbringup waywiser_nav2 waywiser_perception waywiser_rviz2 waywiser_slam waywiser_teleop waywiser_test_runner waywiser_twist_safety
          target-ros2-distro: humble
          vcs-repo-file-url: /tmp/deps.repos
          extra-cmake-args: -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER_LAUNCHER=ccache
