name: Build and Push CI Image (arm64)

on:
  push:
    branches:
      - humble
    paths:
      - ".github/workflows/Dockerfile.ci.arm64"
      - ".github/workflows/docker-ci-arm64.yaml"
      - "Makefile"
      - "waywiser/scripts/bootstrap"
      - ".env.example"
      - ".python-version"
      - ".gitmodules"
      - "pyproject.toml"
      - "uv.lock"
      - "**/package.xml"
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # --- REQUIRED FOR GHA CACHING ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for arm64
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/das-rise/waywiser/ci-image-arm64
          tags: |
            type=raw,value=humble

      - name: Build and push arm64 Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./.github/workflows/Dockerfile.ci.arm64
          platforms: linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Cache optimization
          cache-from: type=gha,scope=ci-image-arm64
          cache-to: type=gha,mode=max,scope=ci-image-arm64
